apiVersion: v1
kind: Service
metadata:
  name: stock-api
  namespace: stock-visualizer
  labels:
    app: stock-api
spec:
  type: ClusterIP
  selector:
    app: stock-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
