apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-api
  namespace: pueyleng
spec:
  ingressClassName: nginx
  rules:
    - host: stock-api.pueyleng.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: stock-api
                port:
                  name: http
